### ISSUE TITLE
Add human-readable description to QKColor, QKPalette, and QKShade.

### ISSUE THREAD

**Issue by sorenmortensen** [georgepstaylor/QuantumKit#21]

**Comment by georgepstaylor** [comment]
Can this be closed now?

**Comment by sorenmortensen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add human-readable descriptions to QKColor instances](https://trello.com/c/ChDB7TnK/13-add-human-readable-descriptions-to-qkcolor-instances)
