### ISSUE TITLE
Update tagline

### ISSUE THREAD

**Issue by sorenmortensen** [georgepstaylor/QuantumKit#8]
The tagline says that the framework is for iOS, but it's been changed to support watchOS, tvOS, and macOS as well.

**Comment by sorenmortensen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update repository tagline](https://trello.com/c/KViNIbL5/4-update-repository-tagline)

**Comment by sorenmortensen** [comment]
@georgepstaylor You didn't update the tagline...

**Comment by georgepstaylor** [comment]
did now ;P
